[package]
name = "async_jsonl_ci"
version = "0.1.0"
edition = "2024"

[dependencies]
gh-workflow-tailcall = { git = "https://github.com/ssddOnTop/gh-workflow/", branch = "fix/change-gh-token-name-from-env" }
