[package]
name = "async_jsonl_ci"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "generate-workflows"
path = "src/bin/generate-workflows.rs"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
gh-workflow-tailcall = "0.5.2"
indexmap = "2.9.0"
