[package]
name = "async_jsonl_ci"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
gh-workflow-tailcall = { version = "0.5.2", git = "https://github.com/ssddOnTop/gh-workflow", branch = "fix/change-gh-token-name-from-env", commit = "6b30b75e8a5d9c8b3c0aad69e4b1ba7bd3d82dbf" }
